---
version: "2.1" # For Windows users

services:

  # 1 Start Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1G -Xmx2G"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2 Scan the files and make a index
  sist2_scan:
    image: simon987/sist2
    restart: "no"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - C:\Users\user\Desktop\thesis papers/:/tmp/es
      - .\my_index/:/my_index
    command: "scan --very-verbose --incremental /tmp/es --output /my_index/idx"

  # 3 Push index to elasticsearch
  sist2_index:
    image: simon987/sist2
    container_name: sist2_index
    restart: "no"
    depends_on:
      sist2_scan:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    volumes:
      - C:\Users\user\Desktop\thesis papers/:/tmp/es
      - .\my_index/:/my_index
    command: "index --very-verbose --force-reset --batch-size 1000 --es-url http://elasticsearch:9200 /my_index/idx"

  # 4 Start the web UI
  sist2_web:
    image: simon987/sist2
    container_name: sist2_web
    restart: "no"
    depends_on:
      sist2_scan:
        condition: service_completed_successfully
      sist2_index:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    ports:
      - "8888:8888"
    volumes:
      - C:\Users\user\Desktop\thesis papers/:/tmp/es
      - .\my_index/:/my_index
    command: "web --very-verbose --bind 0.0.0.0:8888 --es-url http://elasticsearch:9200 /my_index/idx"

volumes:
  documents:
    driver: local
  my_index:
    driver: local
